### ISSUE TITLE
Crash on launch in Linux

### ISSUE THREAD

**Issue by MagmaSKV** [SpikeHD/reMITM#8]
Hello, I have had a problem trying to use the program, this error occurs from multilanguage support (0.4.0) to the newest one (0.6.0), I saw that you fixed this in the newest one but it still happens to me , I don't know if it is because my system is in Spanish or something similar, I leave here what it gives me when I run it:

2024-02-27 19:52:11 | [INFO] == Initializing 2024-02-27 19:52:11 ==
2024-02-27 19:52:11 | [INFO] Redirecting requests to: localhost:3000
2024-02-27 19:52:11 | [INFO] Starting with GUI
2024-02-27 19:52:13 | [INFO] Loading language file: en
2024-02-27 19:52:13 | [WARNING] Error loading language file: en, falling back to english.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No existe el fichero o el directorio" }', src/lang.rs:49:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

In this case, I'm using Arch Linux on its newest kernel so far (6.7.5). I have tried 0.6.0, 0.4.0 and 0.3.0, the last one is the one that works for me so that's why I think the problem is multilanguage since the same thing happens

**Comment by SpikeHD** [comment]
Should be fixed as of 0b49269024afd28c486cf1befedac9483ea01e87, you can try an actions build if you'd like, or just wait for me to upload v0.7.0 which will be in a few minutes
